name: Test S3

on:
  workflow_dispatch:
    inputs:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: keithweaver/aws-s3-github-action@master
      with:
        command: sync --exclude "*.png" --exclude "*/sitemap.xml"
        source: public
        destination: s3://${{ secret.AWS_S3_BUCKET }}/public
        aws_access_key_id: ${{ secret.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
