name: Update Mapping Files

on:
  workflow_dispatch:
    inputs:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  wondible/onetech-prereqs:s3

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: process/node_modules
        key: processor-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-processor-node_modules-${{ hashFiles('**/package-lock.json') }}
          ${{ runner.os }}-processor-node_modules-
          processor-node_modules-
    - name: Install dependencies
      run: cd process && npm install
    - name: Make Directories
      run: mkdir -p public/static/sprites && mkdir -p public/static-edge/sprites
    - name: Download static
      run: s3cmd --no-check-certificate --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY --verbose --human-readable-sizes --stop-on-error --exclude=*.png --exclude=*/pretty-json/* sync s3://$BUCKET/static public/
      env:
        BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: copy edge
      run: cp -R public/static public/static-edge
    - name: file report
      run: ls -R public
    - name: Process Data
      run: cd process && node process.js download sprites
