name: Update Mapping Files

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'

defaults:
  run:
    working-directory: process

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  wondible/onetech-prereqs

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Make Directories
      run: mkdir -p ../public/static/sprites && mkdir -p ../public/static-edge/sprites
    - name: Process Data
      run: npm download sprites
